Controllers/Account/EmployeePositionController.cs
using EmployeeManagment.Models.EmployeeViewModels;
using EmployeeManagment.Models;
using EmployeeManagment.Service;
using Microsoft.AspNetCore.Mvc;

namespace EmployeeManagment.Controllers.Account
{
    public class EmployeePositionController : Controller
    {
        public readonly IEmployeePositionService _employeepositionService;
        public readonly IPositionService _positionService;

        public EmployeePositionController(IEmployeePositionService employeepositionService,IPositionService positionService)
        {
            _employeepositionService = employeepositionService;
            _positionService = positionService;
        }

        public async Task <IActionResult> Index(int eId)
        {
            
            var employeepositions = (await _employeepositionService.GetAllEmployeesPosition()).Where(x=>x.EmployeeId == eId) ; 
            ViewBag.EmployeeId = eId ;
            return View(employeepositions); 
        }

        [HttpGet]
        public IActionResult Create(int eId)
        {

            var model = new EmployeePositionForCreationDto();
            model.Positions = _positionService.GetAllPosition();
            model.EmployeeId = eId;
            return View(model); 
        }
        [HttpPost]
        public IActionResult Create(EmployeePositionForCreationDto model)
        {
            var employeeposition = new Data.EmployeePosition(); 
            employeeposition.EmployeeId = model.EmployeeId;
            employeeposition.PositionId = model.PositionId;


            _employeepositionService.CreateEmployeePosition(employeeposition); 

            return RedirectToAction("Index"); 
        }


        public async Task <IActionResult> Delete(int id) 
        {
            var employeepositionToDelete = await _employeepositionService.GetEmployeePosition(id); 
            _employeepositionService.DeleteEmployeePosition(employeepositionToDelete); 
            return RedirectToAction("Index"); //kthemi ne index pas fshirjes
        }
        [HttpGet]
        public async Task <IActionResult> Edit(int id)
        {
            var employeepositionToEdit = await _employeepositionService.GetEmployeePosition(id); 
            var model = new EmployeePositionForModificationDto(); 
            model.EmployeeId = (int)employeepositionToEdit.EmployeeId;
            model.PositionId = (int)employeepositionToEdit.PositionId;
           
            return View(model);

        }
        [HttpPost]
        public async Task <IActionResult> Edit(EmployeePositionForModificationDto dto)
        {
            var employeepositionToEdit = await _employeepositionService.GetEmployeePosition(dto.Id);
            employeepositionToEdit.EmployeeId = dto.EmployeeId;
            employeepositionToEdit.PositionId = dto.PositionId;

            return RedirectToAction("Index");
        }
        public async Task <IActionResult> Details(int id)
        {
            var employeeposition = _employeepositionService.GetEmployeePosition(id);

            return View(employeeposition);
        }
        public async Task <IActionResult> EmployeePositionIndex(int employee)
        {
            var employeeposition = await _employeepositionService.GetEmployeePositionsByEmployeeId(employee);
            return View(employeeposition);
        }
        [HttpGet]

        public IActionResult CreateEmployeePosition(int employeepositionId)
        {
            var model = new EmployeePositionForCreationDto();
            return View(model);
        }
    }
}

Controllers/EmployeeController.cs
using EmployeeManagment.Data;
using EmployeeManagment.Models;
using EmployeeManagment.Models.EmployeeViewModels;
using EmployeeManagment.Service;
using Microsoft.AspNetCore.Mvc;

namespace EmployeeManagment.Controllers
{
    public class EmployeeController : Controller
    {
        public readonly IEmployeeServices _employeeService;
        public readonly IEmployeePositionService _employeePositionsService;



        public EmployeeController(IEmployeeServices employeeService)
        {
            _employeeService = employeeService;
            _employeePositionsService = _employeePositionsService;
        }

        public IActionResult Index()
        {
            //duhet te marr te gjith employeet nga databasa dhe ti ruaj ne nje variabel
            var employees = _employeeService.GetAllEmployees(); // mar te gjithe employeet duke perdorur metodeen GetALlEmployees qe me ndodhet ne service
            return View(employees); //hapim view e index duke i derguat views employeet si paramatra kujdes : duhet te presim ne view nje list me employee
        }

        [HttpGet]
        public IActionResult Create()
        {
            var model = new EmployeeForCreationDto(); //krijojm nje objekt me modelin qe do perdorim per te krijuar
            return View(model); //kte model do ta dergojme ne view
        }
        [HttpPost]
        public IActionResult Create(EmployeeForCreationDto model) 
        {
            var employee = new Data.Employee(); //krijome objektin bosh qe do ta mbushim me te dhena qe na vine nga view kto te dhena do ti gjejme tek EmployeeForCreationDto
            employee.FirstName = model.FirstName;
            employee.LastName = model.LastName;
            employee.Address = model.Address;  //=> ky proces quhet mapim pra objektin bosh e mbushim me te dhena
            employee.Age = model.Age;
            employee.Gender = model.Gender;

            _employeeService.CreateEmployee(employee); //me kete metod nga servici e ruajme objektin employee ne database

            return RedirectToAction("Index"); //hapi i fundit me te cilin ne pas ruajtjes se employee kthehemi ne index
        }

        
        public IActionResult Delete(int id) //mer nje parameter id per shkak sepse ne duhet te na vij nga view id e employeet qe duam te fshim
        {
            var employeeToDelete =  _employeeService.GetEmployee(id); //per te mare employeen qe duam te fshime me id qe na vjen si parameter
            _employeeService.DeleteEmployee(employeeToDelete); //therrsim servisin dhe aksesojme metoden qe fshin nje employee ne database , duke i derkuar si parameter employeen qe morem me id qe duam te fshim
            return RedirectToAction("Index"); //kthemi ne index pas fshirjes
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var employeeToEdit=_employeeService.GetEmployee(id); // eshte nje variabel e cila merr employee me id-n qe na ka ardhur nga view
            var model = new EmployeeForModificationDto(); // 
            model.FirstName = employeeToEdit.FirstName; 
            model.LastName = employeeToEdit.LastName;
            model.Address = employeeToEdit.Address;  //=> ky proces quhet mapim pra objektin bosh e mbushim me te dhena
            model.Age = employeeToEdit.Age;
            model.Gender = employeeToEdit.Gender;
            return View(model);

        }
        [HttpPost]
        public IActionResult Edit(EmployeeForModificationDto dto)
        {
            var employeeToEdit = _employeeService.GetEmployee(dto.Id);
            employeeToEdit.FirstName = dto.FirstName;
            employeeToEdit.LastName = dto.LastName;
            employeeToEdit.Address = dto.Address;  
            employeeToEdit.Age = dto.Age;
            employeeToEdit.Gender = dto.Gender;
            _employeeService.UpdateEmployee(employeeToEdit);
            return RedirectToAction("Index");
        }
        public IActionResult Details(int id)
        {
            var employee = _employeeService.GetEmployee(id);

                return View(employee);
        }
        public IActionResult EmployeePositionIndex(int employee)
        {
            var employeePositions = _employeePositionsService.GetEmployeePositionsByEmployeeId (employee);
            return View(employeePositions);
        }
        [HttpGet]

        public IActionResult CreateEmployeePosition(int employeeId)
        {
            var model = new EmployeePositionForCreationDto(); 
            return View(model); 
        }

    }
}

Views/Employee/CreateEmployeePosition.cshtml
@model EmployeeManagment.Models.EmployeeViewModels.EmployeePositionForCreationDto

@{
    ViewData["Title"] = "CreateEmployeePosition";
}

<h1>CreateEmployeePosition</h1>

<h4>EmployeePositionForCreationDto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateEmployeePosition">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="PositionId" class="control-label"></label>
                <select asp-for="PositionId" class="form-control">
                    @foreach(var item in Model.Positions)
                    {
                        <option value="@item.Id">@item.Name</option>

                    }
                    </select>
                    <span asp-validation-for="PositionId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Employee/Details.cshtml
@model EmployeeManagment.Data.Employee

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Employee</h4>
    <a asp-action="Index" asp-route-eId="@Model.Id" asp-controller="EmployeePosition">View Employee Position</a>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Views/Employee/Edit.cshtml
@model EmployeeManagment.Models.EmployeeForModificationDto

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>EmployeeForModificationDto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Employee/Index.cshtml
@model IEnumerable<EmployeeManagment.Data.Employee>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id}) |
@*@*@*                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
*@*@*@            </td>
        </tr>
}
    </tbody>
</table>

Views/Employee/create.cshtml
@model EmployeeManagment.Models.EmployeeViewModels.EmployeeForCreationDto

@{
    ViewData["Title"] = "create";
}

<h1>create</h1>

<h4>EmployeeForCreationDto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}